Adds failure error message

diff --git a/.github/workflows/publish-request.yml b/.github/workflows/publish-request.yml
--- a/.github/workflows/publish-request.yml
+++ b/.github/workflows/publish-request.yml
@@ -32,8 +32,43 @@ jobs:
           body: |
            This issue will create a new PR -- wait for it...
 
-      - id: pr-metadata
+      - name: metadata
+        id: pr-metadata
         uses: ./.github/actions/get-pr-metadata
+        continue-on-error: true
+
+      - name: Check outputs
+        if: ${{ steps.metadata.outcome }} == 'failure'
+        run: |
+          echo "Missing title on the front matter section"
+          echo "Provide a valid title and try again"
+      - name: Add comment
+        uses: peter-evans/create-or-update-comment@v1
+        if: ${{ steps.metadata.outcome }} == 'failure'
+        with:
+          issue-number: ${{ github.event.issue.number }}
+          body: |
+            Missing title on the front matter section
+            Provide a valid title and try again  
+      - name: Remove publish-request label
+        uses: szollarp/remove-label-from-issue-action@v1
+        if: ${{ steps.metadata.outcome }} == 'failure'
+        with:
+          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
+          labels: publish-request
+          issueNumber: ${{ github.event.issue.number }}
+
+      - name: Add missing title label
+        uses: szollarp/add-label-to-issue-action@v1
+        if: ${{ steps.metadata.outcome }} == 'failure'
+        with:
+          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
+          labels: missing-title
+          issueNumber: ${{ github.event.issue.number }}
+
+      - name: Exit on failure
+        if: ${{ steps.metadata.outcome }} == 'failure'
+        run: exit 1
       - name: Commits new file
         run: |
           echo "${{ steps.pr-metadata.outputs.body }}" > ${{ steps.pr-metadata.outputs.fileName }}
